//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.12 at 10:36:21 AM CET 
//


package de.fraunhofer.fokus.oefit.schemagen;

/*
 * #%L
 * govapps_data
 * $Id: DeepMultiOptionType.java 566 2014-11-13 15:22:01Z sma $
 * %%
 * Copyright (C) 2013 - 2014 Fraunhofer FOKUS / CC ÖFIT
 * %%
 * Copyright (c) 2,013, Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1) Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 
 * 2) Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 
 * 3) All advertising materials mentioning features or use of this software must 
 *    display the following acknowledgement: 
 *    This product includes software developed by Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT.
 * 
 * 4) Neither the name of the organization nor the names of its contributors may 
 *    be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL 
 * Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeepMultiOptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeepMultiOptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OptionTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NodeRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FreetextRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Subelement" type="{http://oeffentliche-it.de/GovApps-Export}MultiOptionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeepMultiOptionType", propOrder = {
    "optionTitle",
    "nodeRef",
    "freetextRef",
    "subelements"
})
public class DeepMultiOptionType {

    @XmlElement(name = "OptionTitle", required = true)
    protected String optionTitle;
    @XmlElement(name = "NodeRef", required = true)
    protected String nodeRef;
    @XmlElement(name = "FreetextRef")
    protected String freetextRef;
    @XmlElement(name = "Subelement")
    protected List<MultiOptionType> subelements;

    /**
     * Gets the value of the optionTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionTitle() {
        return optionTitle;
    }

    /**
     * Sets the value of the optionTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionTitle(String value) {
        this.optionTitle = value;
    }

    /**
     * Gets the value of the nodeRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeRef() {
        return nodeRef;
    }

    /**
     * Sets the value of the nodeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeRef(String value) {
        this.nodeRef = value;
    }

    /**
     * Gets the value of the freetextRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreetextRef() {
        return freetextRef;
    }

    /**
     * Sets the value of the freetextRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreetextRef(String value) {
        this.freetextRef = value;
    }

    /**
     * Gets the value of the subelements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subelements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubelements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultiOptionType }
     * 
     * 
     */
    public List<MultiOptionType> getSubelements() {
        if (subelements == null) {
            subelements = new ArrayList<MultiOptionType>();
        }
        return this.subelements;
    }

}
