package de.fraunhofer.fokus.movepla.model.impl;

/*
 * #%L
 * govapps_data
 * $Id: Application_EntitlementModelImpl.java 566 2014-11-13 15:22:01Z sma $
 * %%
 * Copyright (C) 2013 - 2014 Fraunhofer FOKUS / CC ÖFIT
 * %%
 * Copyright (c) 2,013, Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1) Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 
 * 2) Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 
 * 3) All advertising materials mentioning features or use of this software must 
 *    display the following acknowledgement: 
 *    This product includes software developed by Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT.
 * 
 * 4) Neither the name of the organization nor the names of its contributors may 
 *    be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL 
 * Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.fraunhofer.fokus.movepla.model.Application_Entitlement;
import de.fraunhofer.fokus.movepla.model.Application_EntitlementModel;
import de.fraunhofer.fokus.movepla.model.Application_EntitlementSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Application_Entitlement service. Represents a row in the &quot;mvp_Application_Entitlement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.fraunhofer.fokus.movepla.model.Application_EntitlementModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Application_EntitlementImpl}.
 * </p>
 *
 * @author jpa
 * @see Application_EntitlementImpl
 * @see de.fraunhofer.fokus.movepla.model.Application_Entitlement
 * @see de.fraunhofer.fokus.movepla.model.Application_EntitlementModel
 * @generated
 */
@JSON(strict = true)
public class Application_EntitlementModelImpl extends BaseModelImpl<Application_Entitlement>
    implements Application_EntitlementModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a application_ entitlement model instance should use the {@link de.fraunhofer.fokus.movepla.model.Application_Entitlement} interface instead.
     */
    public static final String TABLE_NAME = "mvp_Application_Entitlement";
    public static final Object[][] TABLE_COLUMNS = {
            { "applicationEntitlementID", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "name", Types.VARCHAR },
            { "motivation", Types.VARCHAR },
            { "applicationId", Types.BIGINT },
            { "entitlementId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table mvp_Application_Entitlement (applicationEntitlementID LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,motivation VARCHAR(75) null,applicationId LONG,entitlementId LONG)";
    public static final String TABLE_SQL_DROP = "drop table mvp_Application_Entitlement";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.de.fraunhofer.fokus.movepla.model.Application_Entitlement"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.de.fraunhofer.fokus.movepla.model.Application_Entitlement"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.de.fraunhofer.fokus.movepla.model.Application_Entitlement"),
            true);
    public static long APPLICATIONID_COLUMN_BITMASK = 1L;
    public static long COMPANYID_COLUMN_BITMASK = 2L;
    public static long ENTITLEMENTID_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.de.fraunhofer.fokus.movepla.model.Application_Entitlement"));
    private static ClassLoader _classLoader = Application_Entitlement.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            Application_Entitlement.class
        };
    private long _applicationEntitlementID;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private Date _createDate;
    private Date _modifiedDate;
    private String _name;
    private String _motivation;
    private long _applicationId;
    private long _originalApplicationId;
    private boolean _setOriginalApplicationId;
    private long _entitlementId;
    private long _originalEntitlementId;
    private boolean _setOriginalEntitlementId;
    private long _columnBitmask;
    private Application_Entitlement _escapedModelProxy;

    public Application_EntitlementModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Application_Entitlement toModel(
        Application_EntitlementSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Application_Entitlement model = new Application_EntitlementImpl();

        model.setApplicationEntitlementID(soapModel.getApplicationEntitlementID());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setName(soapModel.getName());
        model.setMotivation(soapModel.getMotivation());
        model.setApplicationId(soapModel.getApplicationId());
        model.setEntitlementId(soapModel.getEntitlementId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Application_Entitlement> toModels(
        Application_EntitlementSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Application_Entitlement> models = new ArrayList<Application_Entitlement>(soapModels.length);

        for (Application_EntitlementSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    public long getPrimaryKey() {
        return _applicationEntitlementID;
    }

    public void setPrimaryKey(long primaryKey) {
        setApplicationEntitlementID(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_applicationEntitlementID);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return Application_Entitlement.class;
    }

    public String getModelClassName() {
        return Application_Entitlement.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("applicationEntitlementID", getApplicationEntitlementID());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("name", getName());
        attributes.put("motivation", getMotivation());
        attributes.put("applicationId", getApplicationId());
        attributes.put("entitlementId", getEntitlementId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long applicationEntitlementID = (Long) attributes.get(
                "applicationEntitlementID");

        if (applicationEntitlementID != null) {
            setApplicationEntitlementID(applicationEntitlementID);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String motivation = (String) attributes.get("motivation");

        if (motivation != null) {
            setMotivation(motivation);
        }

        Long applicationId = (Long) attributes.get("applicationId");

        if (applicationId != null) {
            setApplicationId(applicationId);
        }

        Long entitlementId = (Long) attributes.get("entitlementId");

        if (entitlementId != null) {
            setEntitlementId(entitlementId);
        }
    }

    @JSON
    public long getApplicationEntitlementID() {
        return _applicationEntitlementID;
    }

    public void setApplicationEntitlementID(long applicationEntitlementID) {
        _applicationEntitlementID = applicationEntitlementID;
    }

    @JSON
    public long getCompanyId() {
        return _companyId;
    }

    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    public long getUserId() {
        return _userId;
    }

    public void setUserId(long userId) {
        _userId = userId;
    }

    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    public Date getCreateDate() {
        return _createDate;
    }

    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    public void setName(String name) {
        _name = name;
    }

    @JSON
    public String getMotivation() {
        if (_motivation == null) {
            return StringPool.BLANK;
        } else {
            return _motivation;
        }
    }

    public void setMotivation(String motivation) {
        _motivation = motivation;
    }

    @JSON
    public long getApplicationId() {
        return _applicationId;
    }

    public void setApplicationId(long applicationId) {
        _columnBitmask |= APPLICATIONID_COLUMN_BITMASK;

        if (!_setOriginalApplicationId) {
            _setOriginalApplicationId = true;

            _originalApplicationId = _applicationId;
        }

        _applicationId = applicationId;
    }

    public long getOriginalApplicationId() {
        return _originalApplicationId;
    }

    @JSON
    public long getEntitlementId() {
        return _entitlementId;
    }

    public void setEntitlementId(long entitlementId) {
        _columnBitmask |= ENTITLEMENTID_COLUMN_BITMASK;

        if (!_setOriginalEntitlementId) {
            _setOriginalEntitlementId = true;

            _originalEntitlementId = _entitlementId;
        }

        _entitlementId = entitlementId;
    }

    public long getOriginalEntitlementId() {
        return _originalEntitlementId;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Application_Entitlement.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Application_Entitlement toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (Application_Entitlement) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public Object clone() {
        Application_EntitlementImpl application_EntitlementImpl = new Application_EntitlementImpl();

        application_EntitlementImpl.setApplicationEntitlementID(getApplicationEntitlementID());
        application_EntitlementImpl.setCompanyId(getCompanyId());
        application_EntitlementImpl.setUserId(getUserId());
        application_EntitlementImpl.setCreateDate(getCreateDate());
        application_EntitlementImpl.setModifiedDate(getModifiedDate());
        application_EntitlementImpl.setName(getName());
        application_EntitlementImpl.setMotivation(getMotivation());
        application_EntitlementImpl.setApplicationId(getApplicationId());
        application_EntitlementImpl.setEntitlementId(getEntitlementId());

        application_EntitlementImpl.resetOriginalValues();

        return application_EntitlementImpl;
    }

    public int compareTo(Application_Entitlement application_Entitlement) {
        long primaryKey = application_Entitlement.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        Application_Entitlement application_Entitlement = null;

        try {
            application_Entitlement = (Application_Entitlement) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = application_Entitlement.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        Application_EntitlementModelImpl application_EntitlementModelImpl = this;

        application_EntitlementModelImpl._originalCompanyId = application_EntitlementModelImpl._companyId;

        application_EntitlementModelImpl._setOriginalCompanyId = false;

        application_EntitlementModelImpl._originalApplicationId = application_EntitlementModelImpl._applicationId;

        application_EntitlementModelImpl._setOriginalApplicationId = false;

        application_EntitlementModelImpl._originalEntitlementId = application_EntitlementModelImpl._entitlementId;

        application_EntitlementModelImpl._setOriginalEntitlementId = false;

        application_EntitlementModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Application_Entitlement> toCacheModel() {
        Application_EntitlementCacheModel application_EntitlementCacheModel = new Application_EntitlementCacheModel();

        application_EntitlementCacheModel.applicationEntitlementID = getApplicationEntitlementID();

        application_EntitlementCacheModel.companyId = getCompanyId();

        application_EntitlementCacheModel.userId = getUserId();

        Date createDate = getCreateDate();

        if (createDate != null) {
            application_EntitlementCacheModel.createDate = createDate.getTime();
        } else {
            application_EntitlementCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            application_EntitlementCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            application_EntitlementCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        application_EntitlementCacheModel.name = getName();

        String name = application_EntitlementCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            application_EntitlementCacheModel.name = null;
        }

        application_EntitlementCacheModel.motivation = getMotivation();

        String motivation = application_EntitlementCacheModel.motivation;

        if ((motivation != null) && (motivation.length() == 0)) {
            application_EntitlementCacheModel.motivation = null;
        }

        application_EntitlementCacheModel.applicationId = getApplicationId();

        application_EntitlementCacheModel.entitlementId = getEntitlementId();

        return application_EntitlementCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(19);

        sb.append("{applicationEntitlementID=");
        sb.append(getApplicationEntitlementID());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", motivation=");
        sb.append(getMotivation());
        sb.append(", applicationId=");
        sb.append(getApplicationId());
        sb.append(", entitlementId=");
        sb.append(getEntitlementId());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(31);

        sb.append("<model><model-name>");
        sb.append("de.fraunhofer.fokus.movepla.model.Application_Entitlement");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>applicationEntitlementID</column-name><column-value><![CDATA[");
        sb.append(getApplicationEntitlementID());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>motivation</column-name><column-value><![CDATA[");
        sb.append(getMotivation());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>applicationId</column-name><column-value><![CDATA[");
        sb.append(getApplicationId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>entitlementId</column-name><column-value><![CDATA[");
        sb.append(getEntitlementId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
