package de.fraunhofer.fokus.movepla.model.impl;

/*
 * #%L
 * govapps_data
 * $Id: EntitlementModelImpl.java 566 2014-11-13 15:22:01Z sma $
 * %%
 * Copyright (C) 2013 - 2014 Fraunhofer FOKUS / CC ÖFIT
 * %%
 * Copyright (c) 2,013, Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1) Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 
 * 2) Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 
 * 3) All advertising materials mentioning features or use of this software must 
 *    display the following acknowledgement: 
 *    This product includes software developed by Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT.
 * 
 * 4) Neither the name of the organization nor the names of its contributors may 
 *    be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL 
 * Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.fraunhofer.fokus.movepla.model.Entitlement;
import de.fraunhofer.fokus.movepla.model.EntitlementModel;
import de.fraunhofer.fokus.movepla.model.EntitlementSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Entitlement service. Represents a row in the &quot;mvp_Entitlement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.fraunhofer.fokus.movepla.model.EntitlementModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntitlementImpl}.
 * </p>
 *
 * @author jpa
 * @see EntitlementImpl
 * @see de.fraunhofer.fokus.movepla.model.Entitlement
 * @see de.fraunhofer.fokus.movepla.model.EntitlementModel
 * @generated
 */
@JSON(strict = true)
public class EntitlementModelImpl extends BaseModelImpl<Entitlement>
    implements EntitlementModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entitlement model instance should use the {@link de.fraunhofer.fokus.movepla.model.Entitlement} interface instead.
     */
    public static final String TABLE_NAME = "mvp_Entitlement";
    public static final Object[][] TABLE_COLUMNS = {
            { "entitlementId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "entitlementName", Types.VARCHAR },
            { "explanation", Types.VARCHAR },
            { "estimation", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table mvp_Entitlement (entitlementId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,entitlementName VARCHAR(75) null,explanation VARCHAR(75) null,estimation VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table mvp_Entitlement";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.de.fraunhofer.fokus.movepla.model.Entitlement"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.de.fraunhofer.fokus.movepla.model.Entitlement"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.de.fraunhofer.fokus.movepla.model.Entitlement"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.de.fraunhofer.fokus.movepla.model.Entitlement"));
    private static ClassLoader _classLoader = Entitlement.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            Entitlement.class
        };
    private long _entitlementId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private Date _createDate;
    private Date _modifiedDate;
    private String _entitlementName;
    private String _explanation;
    private String _estimation;
    private long _columnBitmask;
    private Entitlement _escapedModelProxy;

    public EntitlementModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Entitlement toModel(EntitlementSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Entitlement model = new EntitlementImpl();

        model.setEntitlementId(soapModel.getEntitlementId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setEntitlementName(soapModel.getEntitlementName());
        model.setExplanation(soapModel.getExplanation());
        model.setEstimation(soapModel.getEstimation());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Entitlement> toModels(EntitlementSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Entitlement> models = new ArrayList<Entitlement>(soapModels.length);

        for (EntitlementSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    public long getPrimaryKey() {
        return _entitlementId;
    }

    public void setPrimaryKey(long primaryKey) {
        setEntitlementId(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_entitlementId);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return Entitlement.class;
    }

    public String getModelClassName() {
        return Entitlement.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("entitlementId", getEntitlementId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("entitlementName", getEntitlementName());
        attributes.put("explanation", getExplanation());
        attributes.put("estimation", getEstimation());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long entitlementId = (Long) attributes.get("entitlementId");

        if (entitlementId != null) {
            setEntitlementId(entitlementId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String entitlementName = (String) attributes.get("entitlementName");

        if (entitlementName != null) {
            setEntitlementName(entitlementName);
        }

        String explanation = (String) attributes.get("explanation");

        if (explanation != null) {
            setExplanation(explanation);
        }

        String estimation = (String) attributes.get("estimation");

        if (estimation != null) {
            setEstimation(estimation);
        }
    }

    @JSON
    public long getEntitlementId() {
        return _entitlementId;
    }

    public void setEntitlementId(long entitlementId) {
        _entitlementId = entitlementId;
    }

    @JSON
    public long getCompanyId() {
        return _companyId;
    }

    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    public long getUserId() {
        return _userId;
    }

    public void setUserId(long userId) {
        _userId = userId;
    }

    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    public Date getCreateDate() {
        return _createDate;
    }

    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    public String getEntitlementName() {
        if (_entitlementName == null) {
            return StringPool.BLANK;
        } else {
            return _entitlementName;
        }
    }

    public void setEntitlementName(String entitlementName) {
        _entitlementName = entitlementName;
    }

    @JSON
    public String getExplanation() {
        if (_explanation == null) {
            return StringPool.BLANK;
        } else {
            return _explanation;
        }
    }

    public void setExplanation(String explanation) {
        _explanation = explanation;
    }

    @JSON
    public String getEstimation() {
        if (_estimation == null) {
            return StringPool.BLANK;
        } else {
            return _estimation;
        }
    }

    public void setEstimation(String estimation) {
        _estimation = estimation;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Entitlement.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Entitlement toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (Entitlement) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public Object clone() {
        EntitlementImpl entitlementImpl = new EntitlementImpl();

        entitlementImpl.setEntitlementId(getEntitlementId());
        entitlementImpl.setCompanyId(getCompanyId());
        entitlementImpl.setUserId(getUserId());
        entitlementImpl.setCreateDate(getCreateDate());
        entitlementImpl.setModifiedDate(getModifiedDate());
        entitlementImpl.setEntitlementName(getEntitlementName());
        entitlementImpl.setExplanation(getExplanation());
        entitlementImpl.setEstimation(getEstimation());

        entitlementImpl.resetOriginalValues();

        return entitlementImpl;
    }

    public int compareTo(Entitlement entitlement) {
        long primaryKey = entitlement.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        Entitlement entitlement = null;

        try {
            entitlement = (Entitlement) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = entitlement.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        EntitlementModelImpl entitlementModelImpl = this;

        entitlementModelImpl._originalCompanyId = entitlementModelImpl._companyId;

        entitlementModelImpl._setOriginalCompanyId = false;

        entitlementModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Entitlement> toCacheModel() {
        EntitlementCacheModel entitlementCacheModel = new EntitlementCacheModel();

        entitlementCacheModel.entitlementId = getEntitlementId();

        entitlementCacheModel.companyId = getCompanyId();

        entitlementCacheModel.userId = getUserId();

        Date createDate = getCreateDate();

        if (createDate != null) {
            entitlementCacheModel.createDate = createDate.getTime();
        } else {
            entitlementCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            entitlementCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            entitlementCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        entitlementCacheModel.entitlementName = getEntitlementName();

        String entitlementName = entitlementCacheModel.entitlementName;

        if ((entitlementName != null) && (entitlementName.length() == 0)) {
            entitlementCacheModel.entitlementName = null;
        }

        entitlementCacheModel.explanation = getExplanation();

        String explanation = entitlementCacheModel.explanation;

        if ((explanation != null) && (explanation.length() == 0)) {
            entitlementCacheModel.explanation = null;
        }

        entitlementCacheModel.estimation = getEstimation();

        String estimation = entitlementCacheModel.estimation;

        if ((estimation != null) && (estimation.length() == 0)) {
            entitlementCacheModel.estimation = null;
        }

        return entitlementCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(17);

        sb.append("{entitlementId=");
        sb.append(getEntitlementId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", entitlementName=");
        sb.append(getEntitlementName());
        sb.append(", explanation=");
        sb.append(getExplanation());
        sb.append(", estimation=");
        sb.append(getEstimation());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(28);

        sb.append("<model><model-name>");
        sb.append("de.fraunhofer.fokus.movepla.model.Entitlement");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>entitlementId</column-name><column-value><![CDATA[");
        sb.append(getEntitlementId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>entitlementName</column-name><column-value><![CDATA[");
        sb.append(getEntitlementName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>explanation</column-name><column-value><![CDATA[");
        sb.append(getExplanation());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>estimation</column-name><column-value><![CDATA[");
        sb.append(getEstimation());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
