package de.fraunhofer.fokus.movepla.model.impl;

/*
 * #%L
 * govapps_data
 * $Id: LanguageModelImpl.java 566 2014-11-13 15:22:01Z sma $
 * %%
 * Copyright (C) 2013 - 2014 Fraunhofer FOKUS / CC ÖFIT
 * %%
 * Copyright (c) 2,013, Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1) Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 
 * 2) Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 
 * 3) All advertising materials mentioning features or use of this software must 
 *    display the following acknowledgement: 
 *    This product includes software developed by Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT.
 * 
 * 4) Neither the name of the organization nor the names of its contributors may 
 *    be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL 
 * Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.fraunhofer.fokus.movepla.model.Language;
import de.fraunhofer.fokus.movepla.model.LanguageModel;
import de.fraunhofer.fokus.movepla.model.LanguageSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Language service. Represents a row in the &quot;mvp_Language&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.fraunhofer.fokus.movepla.model.LanguageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LanguageImpl}.
 * </p>
 *
 * @author jpa
 * @see LanguageImpl
 * @see de.fraunhofer.fokus.movepla.model.Language
 * @see de.fraunhofer.fokus.movepla.model.LanguageModel
 * @generated
 */
@JSON(strict = true)
public class LanguageModelImpl extends BaseModelImpl<Language>
    implements LanguageModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a language model instance should use the {@link de.fraunhofer.fokus.movepla.model.Language} interface instead.
     */
    public static final String TABLE_NAME = "mvp_Language";
    public static final Object[][] TABLE_COLUMNS = {
            { "LanguageId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "languageName", Types.VARCHAR },
            { "languageAbbreviation", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table mvp_Language (LanguageId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,languageName VARCHAR(75) null,languageAbbreviation VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table mvp_Language";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.de.fraunhofer.fokus.movepla.model.Language"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.de.fraunhofer.fokus.movepla.model.Language"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.de.fraunhofer.fokus.movepla.model.Language"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long LANGUAGENAME_COLUMN_BITMASK = 2L;
    public static final String MAPPING_TABLE_MVP_APPLICATION_LANGUAGE_NAME = "mvp_Application_Language";
    public static final Object[][] MAPPING_TABLE_MVP_APPLICATION_LANGUAGE_COLUMNS =
        {
            { "LanguageId", Types.BIGINT },
            { "applicationId", Types.BIGINT }
        };
    public static final String MAPPING_TABLE_MVP_APPLICATION_LANGUAGE_SQL_CREATE =
        "create table mvp_Application_Language (LanguageId LONG not null,applicationId LONG not null,primary key (LanguageId, applicationId))";
    public static final boolean FINDER_CACHE_ENABLED_MVP_APPLICATION_LANGUAGE = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.mvp_Application_Language"),
            true);
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.de.fraunhofer.fokus.movepla.model.Language"));
    private static ClassLoader _classLoader = Language.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            Language.class
        };
    private long _LanguageId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private Date _createDate;
    private Date _modifiedDate;
    private String _languageName;
    private String _originalLanguageName;
    private String _languageAbbreviation;
    private long _columnBitmask;
    private Language _escapedModelProxy;

    public LanguageModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Language toModel(LanguageSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Language model = new LanguageImpl();

        model.setLanguageId(soapModel.getLanguageId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setLanguageName(soapModel.getLanguageName());
        model.setLanguageAbbreviation(soapModel.getLanguageAbbreviation());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Language> toModels(LanguageSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Language> models = new ArrayList<Language>(soapModels.length);

        for (LanguageSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    public long getPrimaryKey() {
        return _LanguageId;
    }

    public void setPrimaryKey(long primaryKey) {
        setLanguageId(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_LanguageId);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return Language.class;
    }

    public String getModelClassName() {
        return Language.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("LanguageId", getLanguageId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("languageName", getLanguageName());
        attributes.put("languageAbbreviation", getLanguageAbbreviation());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long LanguageId = (Long) attributes.get("LanguageId");

        if (LanguageId != null) {
            setLanguageId(LanguageId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String languageName = (String) attributes.get("languageName");

        if (languageName != null) {
            setLanguageName(languageName);
        }

        String languageAbbreviation = (String) attributes.get(
                "languageAbbreviation");

        if (languageAbbreviation != null) {
            setLanguageAbbreviation(languageAbbreviation);
        }
    }

    @JSON
    public long getLanguageId() {
        return _LanguageId;
    }

    public void setLanguageId(long LanguageId) {
        _LanguageId = LanguageId;
    }

    @JSON
    public long getCompanyId() {
        return _companyId;
    }

    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    public long getUserId() {
        return _userId;
    }

    public void setUserId(long userId) {
        _userId = userId;
    }

    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    public Date getCreateDate() {
        return _createDate;
    }

    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    public String getLanguageName() {
        if (_languageName == null) {
            return StringPool.BLANK;
        } else {
            return _languageName;
        }
    }

    public void setLanguageName(String languageName) {
        _columnBitmask |= LANGUAGENAME_COLUMN_BITMASK;

        if (_originalLanguageName == null) {
            _originalLanguageName = _languageName;
        }

        _languageName = languageName;
    }

    public String getOriginalLanguageName() {
        return GetterUtil.getString(_originalLanguageName);
    }

    @JSON
    public String getLanguageAbbreviation() {
        if (_languageAbbreviation == null) {
            return StringPool.BLANK;
        } else {
            return _languageAbbreviation;
        }
    }

    public void setLanguageAbbreviation(String languageAbbreviation) {
        _languageAbbreviation = languageAbbreviation;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Language.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Language toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (Language) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public Object clone() {
        LanguageImpl languageImpl = new LanguageImpl();

        languageImpl.setLanguageId(getLanguageId());
        languageImpl.setCompanyId(getCompanyId());
        languageImpl.setUserId(getUserId());
        languageImpl.setCreateDate(getCreateDate());
        languageImpl.setModifiedDate(getModifiedDate());
        languageImpl.setLanguageName(getLanguageName());
        languageImpl.setLanguageAbbreviation(getLanguageAbbreviation());

        languageImpl.resetOriginalValues();

        return languageImpl;
    }

    public int compareTo(Language language) {
        long primaryKey = language.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        Language language = null;

        try {
            language = (Language) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = language.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        LanguageModelImpl languageModelImpl = this;

        languageModelImpl._originalCompanyId = languageModelImpl._companyId;

        languageModelImpl._setOriginalCompanyId = false;

        languageModelImpl._originalLanguageName = languageModelImpl._languageName;

        languageModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Language> toCacheModel() {
        LanguageCacheModel languageCacheModel = new LanguageCacheModel();

        languageCacheModel.LanguageId = getLanguageId();

        languageCacheModel.companyId = getCompanyId();

        languageCacheModel.userId = getUserId();

        Date createDate = getCreateDate();

        if (createDate != null) {
            languageCacheModel.createDate = createDate.getTime();
        } else {
            languageCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            languageCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            languageCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        languageCacheModel.languageName = getLanguageName();

        String languageName = languageCacheModel.languageName;

        if ((languageName != null) && (languageName.length() == 0)) {
            languageCacheModel.languageName = null;
        }

        languageCacheModel.languageAbbreviation = getLanguageAbbreviation();

        String languageAbbreviation = languageCacheModel.languageAbbreviation;

        if ((languageAbbreviation != null) &&
                (languageAbbreviation.length() == 0)) {
            languageCacheModel.languageAbbreviation = null;
        }

        return languageCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(15);

        sb.append("{LanguageId=");
        sb.append(getLanguageId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", languageName=");
        sb.append(getLanguageName());
        sb.append(", languageAbbreviation=");
        sb.append(getLanguageAbbreviation());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(25);

        sb.append("<model><model-name>");
        sb.append("de.fraunhofer.fokus.movepla.model.Language");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>LanguageId</column-name><column-value><![CDATA[");
        sb.append(getLanguageId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>languageName</column-name><column-value><![CDATA[");
        sb.append(getLanguageName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>languageAbbreviation</column-name><column-value><![CDATA[");
        sb.append(getLanguageAbbreviation());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
