package de.fraunhofer.fokus.movepla.model.impl;

/*
 * #%L
 * govapps_data
 * $Id: LinkModelImpl.java 566 2014-11-13 15:22:01Z sma $
 * %%
 * Copyright (C) 2013 - 2014 Fraunhofer FOKUS / CC ÖFIT
 * %%
 * Copyright (c) 2,013, Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1) Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 
 * 2) Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 
 * 3) All advertising materials mentioning features or use of this software must 
 *    display the following acknowledgement: 
 *    This product includes software developed by Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT.
 * 
 * 4) Neither the name of the organization nor the names of its contributors may 
 *    be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL 
 * Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.fraunhofer.fokus.movepla.model.Link;
import de.fraunhofer.fokus.movepla.model.LinkModel;
import de.fraunhofer.fokus.movepla.model.LinkSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Link service. Represents a row in the &quot;mvp_Link&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.fraunhofer.fokus.movepla.model.LinkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LinkImpl}.
 * </p>
 *
 * @author jpa
 * @see LinkImpl
 * @see de.fraunhofer.fokus.movepla.model.Link
 * @see de.fraunhofer.fokus.movepla.model.LinkModel
 * @generated
 */
@JSON(strict = true)
public class LinkModelImpl extends BaseModelImpl<Link> implements LinkModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a link model instance should use the {@link de.fraunhofer.fokus.movepla.model.Link} interface instead.
     */
    public static final String TABLE_NAME = "mvp_Link";
    public static final Object[][] TABLE_COLUMNS = {
            { "linkId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "displayName", Types.VARCHAR },
            { "type_", Types.INTEGER },
            { "url", Types.VARCHAR },
            { "applicationId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table mvp_Link (linkId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,displayName VARCHAR(75) null,type_ INTEGER,url VARCHAR(75) null,applicationId LONG)";
    public static final String TABLE_SQL_DROP = "drop table mvp_Link";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.de.fraunhofer.fokus.movepla.model.Link"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.de.fraunhofer.fokus.movepla.model.Link"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.de.fraunhofer.fokus.movepla.model.Link"),
            true);
    public static long APPLICATIONID_COLUMN_BITMASK = 1L;
    public static long COMPANYID_COLUMN_BITMASK = 2L;
    public static long TYPE_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.de.fraunhofer.fokus.movepla.model.Link"));
    private static ClassLoader _classLoader = Link.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            Link.class
        };
    private long _linkId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private Date _createDate;
    private Date _modifiedDate;
    private String _displayName;
    private int _type;
    private int _originalType;
    private boolean _setOriginalType;
    private String _url;
    private long _applicationId;
    private long _originalApplicationId;
    private boolean _setOriginalApplicationId;
    private long _columnBitmask;
    private Link _escapedModelProxy;

    public LinkModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Link toModel(LinkSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Link model = new LinkImpl();

        model.setLinkId(soapModel.getLinkId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setDisplayName(soapModel.getDisplayName());
        model.setType(soapModel.getType());
        model.setUrl(soapModel.getUrl());
        model.setApplicationId(soapModel.getApplicationId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Link> toModels(LinkSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Link> models = new ArrayList<Link>(soapModels.length);

        for (LinkSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    public long getPrimaryKey() {
        return _linkId;
    }

    public void setPrimaryKey(long primaryKey) {
        setLinkId(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_linkId);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return Link.class;
    }

    public String getModelClassName() {
        return Link.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("linkId", getLinkId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("displayName", getDisplayName());
        attributes.put("type", getType());
        attributes.put("url", getUrl());
        attributes.put("applicationId", getApplicationId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long linkId = (Long) attributes.get("linkId");

        if (linkId != null) {
            setLinkId(linkId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String displayName = (String) attributes.get("displayName");

        if (displayName != null) {
            setDisplayName(displayName);
        }

        Integer type = (Integer) attributes.get("type");

        if (type != null) {
            setType(type);
        }

        String url = (String) attributes.get("url");

        if (url != null) {
            setUrl(url);
        }

        Long applicationId = (Long) attributes.get("applicationId");

        if (applicationId != null) {
            setApplicationId(applicationId);
        }
    }

    @JSON
    public long getLinkId() {
        return _linkId;
    }

    public void setLinkId(long linkId) {
        _linkId = linkId;
    }

    @JSON
    public long getCompanyId() {
        return _companyId;
    }

    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    public long getUserId() {
        return _userId;
    }

    public void setUserId(long userId) {
        _userId = userId;
    }

    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    public Date getCreateDate() {
        return _createDate;
    }

    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    public String getDisplayName() {
        if (_displayName == null) {
            return StringPool.BLANK;
        } else {
            return _displayName;
        }
    }

    public void setDisplayName(String displayName) {
        _displayName = displayName;
    }

    @JSON
    public int getType() {
        return _type;
    }

    public void setType(int type) {
        _columnBitmask |= TYPE_COLUMN_BITMASK;

        if (!_setOriginalType) {
            _setOriginalType = true;

            _originalType = _type;
        }

        _type = type;
    }

    public int getOriginalType() {
        return _originalType;
    }

    @JSON
    public String getUrl() {
        if (_url == null) {
            return StringPool.BLANK;
        } else {
            return _url;
        }
    }

    public void setUrl(String url) {
        _url = url;
    }

    @JSON
    public long getApplicationId() {
        return _applicationId;
    }

    public void setApplicationId(long applicationId) {
        _columnBitmask |= APPLICATIONID_COLUMN_BITMASK;

        if (!_setOriginalApplicationId) {
            _setOriginalApplicationId = true;

            _originalApplicationId = _applicationId;
        }

        _applicationId = applicationId;
    }

    public long getOriginalApplicationId() {
        return _originalApplicationId;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Link.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Link toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (Link) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public Object clone() {
        LinkImpl linkImpl = new LinkImpl();

        linkImpl.setLinkId(getLinkId());
        linkImpl.setCompanyId(getCompanyId());
        linkImpl.setUserId(getUserId());
        linkImpl.setCreateDate(getCreateDate());
        linkImpl.setModifiedDate(getModifiedDate());
        linkImpl.setDisplayName(getDisplayName());
        linkImpl.setType(getType());
        linkImpl.setUrl(getUrl());
        linkImpl.setApplicationId(getApplicationId());

        linkImpl.resetOriginalValues();

        return linkImpl;
    }

    public int compareTo(Link link) {
        long primaryKey = link.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        Link link = null;

        try {
            link = (Link) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = link.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        LinkModelImpl linkModelImpl = this;

        linkModelImpl._originalCompanyId = linkModelImpl._companyId;

        linkModelImpl._setOriginalCompanyId = false;

        linkModelImpl._originalType = linkModelImpl._type;

        linkModelImpl._setOriginalType = false;

        linkModelImpl._originalApplicationId = linkModelImpl._applicationId;

        linkModelImpl._setOriginalApplicationId = false;

        linkModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Link> toCacheModel() {
        LinkCacheModel linkCacheModel = new LinkCacheModel();

        linkCacheModel.linkId = getLinkId();

        linkCacheModel.companyId = getCompanyId();

        linkCacheModel.userId = getUserId();

        Date createDate = getCreateDate();

        if (createDate != null) {
            linkCacheModel.createDate = createDate.getTime();
        } else {
            linkCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            linkCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            linkCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        linkCacheModel.displayName = getDisplayName();

        String displayName = linkCacheModel.displayName;

        if ((displayName != null) && (displayName.length() == 0)) {
            linkCacheModel.displayName = null;
        }

        linkCacheModel.type = getType();

        linkCacheModel.url = getUrl();

        String url = linkCacheModel.url;

        if ((url != null) && (url.length() == 0)) {
            linkCacheModel.url = null;
        }

        linkCacheModel.applicationId = getApplicationId();

        return linkCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(19);

        sb.append("{linkId=");
        sb.append(getLinkId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", displayName=");
        sb.append(getDisplayName());
        sb.append(", type=");
        sb.append(getType());
        sb.append(", url=");
        sb.append(getUrl());
        sb.append(", applicationId=");
        sb.append(getApplicationId());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(31);

        sb.append("<model><model-name>");
        sb.append("de.fraunhofer.fokus.movepla.model.Link");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>linkId</column-name><column-value><![CDATA[");
        sb.append(getLinkId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>displayName</column-name><column-value><![CDATA[");
        sb.append(getDisplayName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>type</column-name><column-value><![CDATA[");
        sb.append(getType());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>url</column-name><column-value><![CDATA[");
        sb.append(getUrl());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>applicationId</column-name><column-value><![CDATA[");
        sb.append(getApplicationId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
