package de.fraunhofer.fokus.movepla.model.impl;

/*
 * #%L
 * govapps_data
 * $Id: RegionModelImpl.java 566 2014-11-13 15:22:01Z sma $
 * %%
 * Copyright (C) 2013 - 2014 Fraunhofer FOKUS / CC ÖFIT
 * %%
 * Copyright (c) 2,013, Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1) Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 
 * 2) Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 
 * 3) All advertising materials mentioning features or use of this software must 
 *    display the following acknowledgement: 
 *    This product includes software developed by Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT.
 * 
 * 4) Neither the name of the organization nor the names of its contributors may 
 *    be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL 
 * Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.fraunhofer.fokus.movepla.model.Region;
import de.fraunhofer.fokus.movepla.model.RegionModel;
import de.fraunhofer.fokus.movepla.model.RegionSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Region service. Represents a row in the &quot;mvp_Region&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.fraunhofer.fokus.movepla.model.RegionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegionImpl}.
 * </p>
 *
 * @author jpa
 * @see RegionImpl
 * @see de.fraunhofer.fokus.movepla.model.Region
 * @see de.fraunhofer.fokus.movepla.model.RegionModel
 * @generated
 */
@JSON(strict = true)
public class RegionModelImpl extends BaseModelImpl<Region>
    implements RegionModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a region model instance should use the {@link de.fraunhofer.fokus.movepla.model.Region} interface instead.
     */
    public static final String TABLE_NAME = "mvp_Region";
    public static final Object[][] TABLE_COLUMNS = {
            { "regionId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "name", Types.VARCHAR },
            { "ags", Types.INTEGER },
            { "coordniates_x", Types.DOUBLE },
            { "coordniates_y", Types.DOUBLE },
            { "parentRegion", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table mvp_Region (regionId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,ags INTEGER,coordniates_x DOUBLE,coordniates_y DOUBLE,parentRegion LONG)";
    public static final String TABLE_SQL_DROP = "drop table mvp_Region";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.de.fraunhofer.fokus.movepla.model.Region"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.de.fraunhofer.fokus.movepla.model.Region"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.de.fraunhofer.fokus.movepla.model.Region"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long NAME_COLUMN_BITMASK = 2L;
    public static long PARENTREGION_COLUMN_BITMASK = 4L;
    public static final String MAPPING_TABLE_MVP_APPLICATION_REGION_NAME = "mvp_Application_Region";
    public static final Object[][] MAPPING_TABLE_MVP_APPLICATION_REGION_COLUMNS = {
            { "regionId", Types.BIGINT },
            { "applicationId", Types.BIGINT }
        };
    public static final String MAPPING_TABLE_MVP_APPLICATION_REGION_SQL_CREATE = "create table mvp_Application_Region (regionId LONG not null,applicationId LONG not null,primary key (regionId, applicationId))";
    public static final boolean FINDER_CACHE_ENABLED_MVP_APPLICATION_REGION = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.mvp_Application_Region"),
            true);
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.de.fraunhofer.fokus.movepla.model.Region"));
    private static ClassLoader _classLoader = Region.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            Region.class
        };
    private long _regionId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private Date _createDate;
    private Date _modifiedDate;
    private String _name;
    private String _originalName;
    private int _ags;
    private double _coordniates_x;
    private double _coordniates_y;
    private long _parentRegion;
    private long _originalParentRegion;
    private boolean _setOriginalParentRegion;
    private long _columnBitmask;
    private Region _escapedModelProxy;

    public RegionModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Region toModel(RegionSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Region model = new RegionImpl();

        model.setRegionId(soapModel.getRegionId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setName(soapModel.getName());
        model.setAgs(soapModel.getAgs());
        model.setCoordniates_x(soapModel.getCoordniates_x());
        model.setCoordniates_y(soapModel.getCoordniates_y());
        model.setParentRegion(soapModel.getParentRegion());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Region> toModels(RegionSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Region> models = new ArrayList<Region>(soapModels.length);

        for (RegionSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    public long getPrimaryKey() {
        return _regionId;
    }

    public void setPrimaryKey(long primaryKey) {
        setRegionId(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_regionId);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return Region.class;
    }

    public String getModelClassName() {
        return Region.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("regionId", getRegionId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("name", getName());
        attributes.put("ags", getAgs());
        attributes.put("coordniates_x", getCoordniates_x());
        attributes.put("coordniates_y", getCoordniates_y());
        attributes.put("parentRegion", getParentRegion());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long regionId = (Long) attributes.get("regionId");

        if (regionId != null) {
            setRegionId(regionId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        Integer ags = (Integer) attributes.get("ags");

        if (ags != null) {
            setAgs(ags);
        }

        Double coordniates_x = (Double) attributes.get("coordniates_x");

        if (coordniates_x != null) {
            setCoordniates_x(coordniates_x);
        }

        Double coordniates_y = (Double) attributes.get("coordniates_y");

        if (coordniates_y != null) {
            setCoordniates_y(coordniates_y);
        }

        Long parentRegion = (Long) attributes.get("parentRegion");

        if (parentRegion != null) {
            setParentRegion(parentRegion);
        }
    }

    @JSON
    public long getRegionId() {
        return _regionId;
    }

    public void setRegionId(long regionId) {
        _regionId = regionId;
    }

    @JSON
    public long getCompanyId() {
        return _companyId;
    }

    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    public long getUserId() {
        return _userId;
    }

    public void setUserId(long userId) {
        _userId = userId;
    }

    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    public Date getCreateDate() {
        return _createDate;
    }

    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    public void setName(String name) {
        _columnBitmask |= NAME_COLUMN_BITMASK;

        if (_originalName == null) {
            _originalName = _name;
        }

        _name = name;
    }

    public String getOriginalName() {
        return GetterUtil.getString(_originalName);
    }

    @JSON
    public int getAgs() {
        return _ags;
    }

    public void setAgs(int ags) {
        _ags = ags;
    }

    @JSON
    public double getCoordniates_x() {
        return _coordniates_x;
    }

    public void setCoordniates_x(double coordniates_x) {
        _coordniates_x = coordniates_x;
    }

    @JSON
    public double getCoordniates_y() {
        return _coordniates_y;
    }

    public void setCoordniates_y(double coordniates_y) {
        _coordniates_y = coordniates_y;
    }

    @JSON
    public long getParentRegion() {
        return _parentRegion;
    }

    public void setParentRegion(long parentRegion) {
        _columnBitmask |= PARENTREGION_COLUMN_BITMASK;

        if (!_setOriginalParentRegion) {
            _setOriginalParentRegion = true;

            _originalParentRegion = _parentRegion;
        }

        _parentRegion = parentRegion;
    }

    public long getOriginalParentRegion() {
        return _originalParentRegion;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Region.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Region toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (Region) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public Object clone() {
        RegionImpl regionImpl = new RegionImpl();

        regionImpl.setRegionId(getRegionId());
        regionImpl.setCompanyId(getCompanyId());
        regionImpl.setUserId(getUserId());
        regionImpl.setCreateDate(getCreateDate());
        regionImpl.setModifiedDate(getModifiedDate());
        regionImpl.setName(getName());
        regionImpl.setAgs(getAgs());
        regionImpl.setCoordniates_x(getCoordniates_x());
        regionImpl.setCoordniates_y(getCoordniates_y());
        regionImpl.setParentRegion(getParentRegion());

        regionImpl.resetOriginalValues();

        return regionImpl;
    }

    public int compareTo(Region region) {
        long primaryKey = region.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        Region region = null;

        try {
            region = (Region) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = region.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        RegionModelImpl regionModelImpl = this;

        regionModelImpl._originalCompanyId = regionModelImpl._companyId;

        regionModelImpl._setOriginalCompanyId = false;

        regionModelImpl._originalName = regionModelImpl._name;

        regionModelImpl._originalParentRegion = regionModelImpl._parentRegion;

        regionModelImpl._setOriginalParentRegion = false;

        regionModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Region> toCacheModel() {
        RegionCacheModel regionCacheModel = new RegionCacheModel();

        regionCacheModel.regionId = getRegionId();

        regionCacheModel.companyId = getCompanyId();

        regionCacheModel.userId = getUserId();

        Date createDate = getCreateDate();

        if (createDate != null) {
            regionCacheModel.createDate = createDate.getTime();
        } else {
            regionCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            regionCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            regionCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        regionCacheModel.name = getName();

        String name = regionCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            regionCacheModel.name = null;
        }

        regionCacheModel.ags = getAgs();

        regionCacheModel.coordniates_x = getCoordniates_x();

        regionCacheModel.coordniates_y = getCoordniates_y();

        regionCacheModel.parentRegion = getParentRegion();

        return regionCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(21);

        sb.append("{regionId=");
        sb.append(getRegionId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", ags=");
        sb.append(getAgs());
        sb.append(", coordniates_x=");
        sb.append(getCoordniates_x());
        sb.append(", coordniates_y=");
        sb.append(getCoordniates_y());
        sb.append(", parentRegion=");
        sb.append(getParentRegion());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(34);

        sb.append("<model><model-name>");
        sb.append("de.fraunhofer.fokus.movepla.model.Region");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>regionId</column-name><column-value><![CDATA[");
        sb.append(getRegionId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ags</column-name><column-value><![CDATA[");
        sb.append(getAgs());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>coordniates_x</column-name><column-value><![CDATA[");
        sb.append(getCoordniates_x());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>coordniates_y</column-name><column-value><![CDATA[");
        sb.append(getCoordniates_y());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>parentRegion</column-name><column-value><![CDATA[");
        sb.append(getParentRegion());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
