package de.fraunhofer.fokus.movepla.model;

/*
 * #%L
 * govapps_data
 * $Id: Application_EntitlementModel.java 566 2014-11-13 15:22:01Z sma $
 * %%
 * Copyright (C) 2013 - 2014 Fraunhofer FOKUS / CC ÖFIT
 * %%
 * Copyright (c) 2,013, Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1) Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 
 * 2) Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 
 * 3) All advertising materials mentioning features or use of this software must 
 *    display the following acknowledgement: 
 *    This product includes software developed by Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT.
 * 
 * 4) Neither the name of the organization nor the names of its contributors may 
 *    be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL 
 * Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Application_Entitlement service. Represents a row in the &quot;mvp_Application_Entitlement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.movepla.model.impl.Application_EntitlementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.movepla.model.impl.Application_EntitlementImpl}.
 * </p>
 *
 * @author jpa
 * @see Application_Entitlement
 * @see de.fraunhofer.fokus.movepla.model.impl.Application_EntitlementImpl
 * @see de.fraunhofer.fokus.movepla.model.impl.Application_EntitlementModelImpl
 * @generated
 */
public interface Application_EntitlementModel extends BaseModel<Application_Entitlement> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a application_ entitlement model instance should use the {@link Application_Entitlement} interface instead.
     */

    /**
     * Returns the primary key of this application_ entitlement.
     *
     * @return the primary key of this application_ entitlement
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this application_ entitlement.
     *
     * @param primaryKey the primary key of this application_ entitlement
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the application entitlement i d of this application_ entitlement.
     *
     * @return the application entitlement i d of this application_ entitlement
     */
    public long getApplicationEntitlementID();

    /**
     * Sets the application entitlement i d of this application_ entitlement.
     *
     * @param applicationEntitlementID the application entitlement i d of this application_ entitlement
     */
    public void setApplicationEntitlementID(long applicationEntitlementID);

    /**
     * Returns the company ID of this application_ entitlement.
     *
     * @return the company ID of this application_ entitlement
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this application_ entitlement.
     *
     * @param companyId the company ID of this application_ entitlement
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this application_ entitlement.
     *
     * @return the user ID of this application_ entitlement
     */
    public long getUserId();

    /**
     * Sets the user ID of this application_ entitlement.
     *
     * @param userId the user ID of this application_ entitlement
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this application_ entitlement.
     *
     * @return the user uuid of this application_ entitlement
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this application_ entitlement.
     *
     * @param userUuid the user uuid of this application_ entitlement
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this application_ entitlement.
     *
     * @return the create date of this application_ entitlement
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this application_ entitlement.
     *
     * @param createDate the create date of this application_ entitlement
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this application_ entitlement.
     *
     * @return the modified date of this application_ entitlement
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this application_ entitlement.
     *
     * @param modifiedDate the modified date of this application_ entitlement
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this application_ entitlement.
     *
     * @return the name of this application_ entitlement
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this application_ entitlement.
     *
     * @param name the name of this application_ entitlement
     */
    public void setName(String name);

    /**
     * Returns the motivation of this application_ entitlement.
     *
     * @return the motivation of this application_ entitlement
     */
    @AutoEscape
    public String getMotivation();

    /**
     * Sets the motivation of this application_ entitlement.
     *
     * @param motivation the motivation of this application_ entitlement
     */
    public void setMotivation(String motivation);

    /**
     * Returns the application ID of this application_ entitlement.
     *
     * @return the application ID of this application_ entitlement
     */
    public long getApplicationId();

    /**
     * Sets the application ID of this application_ entitlement.
     *
     * @param applicationId the application ID of this application_ entitlement
     */
    public void setApplicationId(long applicationId);

    /**
     * Returns the entitlement ID of this application_ entitlement.
     *
     * @return the entitlement ID of this application_ entitlement
     */
    public long getEntitlementId();

    /**
     * Sets the entitlement ID of this application_ entitlement.
     *
     * @param entitlementId the entitlement ID of this application_ entitlement
     */
    public void setEntitlementId(long entitlementId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Application_Entitlement application_Entitlement);

    public int hashCode();

    public CacheModel<Application_Entitlement> toCacheModel();

    public Application_Entitlement toEscapedModel();

    public String toString();

    public String toXmlString();
}
