package de.fraunhofer.fokus.movepla.model;

/*
 * #%L
 * govapps_data
 * $Id: ApplicationModel.java 566 2014-11-13 15:22:01Z sma $
 * %%
 * Copyright (C) 2013 - 2014 Fraunhofer FOKUS / CC ÖFIT
 * %%
 * Copyright (c) 2,013, Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1) Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 
 * 2) Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 
 * 3) All advertising materials mentioning features or use of this software must 
 *    display the following acknowledgement: 
 *    This product includes software developed by Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT.
 * 
 * 4) Neither the name of the organization nor the names of its contributors may 
 *    be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL 
 * Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Application service. Represents a row in the &quot;mvp_Application&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.movepla.model.impl.ApplicationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.movepla.model.impl.ApplicationImpl}.
 * </p>
 *
 * @author jpa
 * @see Application
 * @see de.fraunhofer.fokus.movepla.model.impl.ApplicationImpl
 * @see de.fraunhofer.fokus.movepla.model.impl.ApplicationModelImpl
 * @generated
 */
public interface ApplicationModel extends BaseModel<Application> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a application model instance should use the {@link Application} interface instead.
     */

    /**
     * Returns the primary key of this application.
     *
     * @return the primary key of this application
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this application.
     *
     * @param primaryKey the primary key of this application
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the application ID of this application.
     *
     * @return the application ID of this application
     */
    public long getApplicationId();

    /**
     * Sets the application ID of this application.
     *
     * @param applicationId the application ID of this application
     */
    public void setApplicationId(long applicationId);

    /**
     * Returns the company ID of this application.
     *
     * @return the company ID of this application
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this application.
     *
     * @param companyId the company ID of this application
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this application.
     *
     * @return the user ID of this application
     */
    public long getUserId();

    /**
     * Sets the user ID of this application.
     *
     * @param userId the user ID of this application
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this application.
     *
     * @return the user uuid of this application
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this application.
     *
     * @param userUuid the user uuid of this application
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this application.
     *
     * @return the create date of this application
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this application.
     *
     * @param createDate the create date of this application
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this application.
     *
     * @return the modified date of this application
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this application.
     *
     * @param modifiedDate the modified date of this application
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this application.
     *
     * @return the name of this application
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this application.
     *
     * @param name the name of this application
     */
    public void setName(String name);

    /**
     * Returns the description of this application.
     *
     * @return the description of this application
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this application.
     *
     * @param description the description of this application
     */
    public void setDescription(String description);

    /**
     * Returns the version of this application.
     *
     * @return the version of this application
     */
    @AutoEscape
    public String getVersion();

    /**
     * Sets the version of this application.
     *
     * @param version the version of this application
     */
    public void setVersion(String version);

    /**
     * Returns the version information of this application.
     *
     * @return the version information of this application
     */
    @AutoEscape
    public String getVersionInformation();

    /**
     * Sets the version information of this application.
     *
     * @param versionInformation the version information of this application
     */
    public void setVersionInformation(String versionInformation);

    /**
     * Returns the size of this application.
     *
     * @return the size of this application
     */
    public int getSize();

    /**
     * Sets the size of this application.
     *
     * @param size the size of this application
     */
    public void setSize(int size);

    /**
     * Returns the first publishing date of this application.
     *
     * @return the first publishing date of this application
     */
    public Date getFirstPublishingDate();

    /**
     * Sets the first publishing date of this application.
     *
     * @param firstPublishingDate the first publishing date of this application
     */
    public void setFirstPublishingDate(Date firstPublishingDate);

    /**
     * Returns the last modified date of this application.
     *
     * @return the last modified date of this application
     */
    public Date getLastModifiedDate();

    /**
     * Sets the last modified date of this application.
     *
     * @param lastModifiedDate the last modified date of this application
     */
    public void setLastModifiedDate(Date lastModifiedDate);

    /**
     * Returns the logo image ID of this application.
     *
     * @return the logo image ID of this application
     */
    public long getLogoImageId();

    /**
     * Sets the logo image ID of this application.
     *
     * @param logoImageId the logo image ID of this application
     */
    public void setLogoImageId(long logoImageId);

    /**
     * Returns the fee of this application.
     *
     * @return the fee of this application
     */
    public int getFee();

    /**
     * Sets the fee of this application.
     *
     * @param fee the fee of this application
     */
    public void setFee(int fee);

    /**
     * Returns the target o s of this application.
     *
     * @return the target o s of this application
     */
    @AutoEscape
    public String getTargetOS();

    /**
     * Sets the target o s of this application.
     *
     * @param targetOS the target o s of this application
     */
    public void setTargetOS(String targetOS);

    /**
     * Returns the min target o s version of this application.
     *
     * @return the min target o s version of this application
     */
    public int getMinTargetOSVersion();

    /**
     * Sets the min target o s version of this application.
     *
     * @param minTargetOSVersion the min target o s version of this application
     */
    public void setMinTargetOSVersion(int minTargetOSVersion);

    /**
     * Returns the target category of this application.
     *
     * @return the target category of this application
     */
    @AutoEscape
    public String getTargetCategory();

    /**
     * Sets the target category of this application.
     *
     * @param targetCategory the target category of this application
     */
    public void setTargetCategory(String targetCategory);

    /**
     * Returns the life cycle status of this application.
     *
     * @return the life cycle status of this application
     */
    public int getLifeCycleStatus();

    /**
     * Sets the life cycle status of this application.
     *
     * @param lifeCycleStatus the life cycle status of this application
     */
    public void setLifeCycleStatus(int lifeCycleStatus);

    /**
     * Returns the verified date of this application.
     *
     * @return the verified date of this application
     */
    public Date getVerifiedDate();

    /**
     * Sets the verified date of this application.
     *
     * @param verifiedDate the verified date of this application
     */
    public void setVerifiedDate(Date verifiedDate);

    /**
     * Returns the category string of this application.
     *
     * @return the category string of this application
     */
    @AutoEscape
    public String getCategoryString();

    /**
     * Sets the category string of this application.
     *
     * @param categoryString the category string of this application
     */
    public void setCategoryString(String categoryString);

    /**
     * Returns the region string of this application.
     *
     * @return the region string of this application
     */
    @AutoEscape
    public String getRegionString();

    /**
     * Sets the region string of this application.
     *
     * @param regionString the region string of this application
     */
    public void setRegionString(String regionString);

    /**
     * Returns the life cycle status string of this application.
     *
     * @return the life cycle status string of this application
     */
    @AutoEscape
    public String getLifeCycleStatusString();

    /**
     * Sets the life cycle status string of this application.
     *
     * @param lifeCycleStatusString the life cycle status string of this application
     */
    public void setLifeCycleStatusString(String lifeCycleStatusString);

    /**
     * Returns the legal details of this application.
     *
     * @return the legal details of this application
     */
    @AutoEscape
    public String getLegalDetails();

    /**
     * Sets the legal details of this application.
     *
     * @param legalDetails the legal details of this application
     */
    public void setLegalDetails(String legalDetails);

    /**
     * Returns the developer of this application.
     *
     * @return the developer of this application
     */
    @AutoEscape
    public String getDeveloper();

    /**
     * Sets the developer of this application.
     *
     * @param developer the developer of this application
     */
    public void setDeveloper(String developer);

    /**
     * Returns the details viewed of this application.
     *
     * @return the details viewed of this application
     */
    public long getDetailsViewed();

    /**
     * Sets the details viewed of this application.
     *
     * @param detailsViewed the details viewed of this application
     */
    public void setDetailsViewed(long detailsViewed);

    /**
     * Returns the link clicked of this application.
     *
     * @return the link clicked of this application
     */
    public long getLinkClicked();

    /**
     * Sets the link clicked of this application.
     *
     * @param linkClicked the link clicked of this application
     */
    public void setLinkClicked(long linkClicked);

    /**
     * Returns the use open data of this application.
     *
     * @return the use open data of this application
     */
    public int getUseOpenData();

    /**
     * Sets the use open data of this application.
     *
     * @param useOpenData the use open data of this application
     */
    public void setUseOpenData(int useOpenData);

    /**
     * Returns the sector of this application.
     *
     * @return the sector of this application
     */
    @AutoEscape
    public String getSector();

    /**
     * Sets the sector of this application.
     *
     * @param Sector the sector of this application
     */
    public void setSector(String Sector);

    /**
     * Returns the license of this application.
     *
     * @return the license of this application
     */
    @AutoEscape
    public String getLicense();

    /**
     * Sets the license of this application.
     *
     * @param License the license of this application
     */
    public void setLicense(String License);

    /**
     * Returns the related application ID of this application.
     *
     * @return the related application ID of this application
     */
    @AutoEscape
    public String getRelatedApplicationId();

    /**
     * Sets the related application ID of this application.
     *
     * @param relatedApplicationId the related application ID of this application
     */
    public void setRelatedApplicationId(String relatedApplicationId);

    /**
     * Returns the new version ID of this application.
     *
     * @return the new version ID of this application
     */
    public long getNewVersionId();

    /**
     * Sets the new version ID of this application.
     *
     * @param newVersionId the new version ID of this application
     */
    public void setNewVersionId(long newVersionId);

    /**
     * Returns the old version ID of this application.
     *
     * @return the old version ID of this application
     */
    public long getOldVersionId();

    /**
     * Sets the old version ID of this application.
     *
     * @param oldVersionId the old version ID of this application
     */
    public void setOldVersionId(long oldVersionId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Application application);

    public int hashCode();

    public CacheModel<Application> toCacheModel();

    public Application toEscapedModel();

    public String toString();

    public String toXmlString();
}
