package de.fraunhofer.fokus.movepla.model;

/*
 * #%L
 * govapps_data
 * $Id: CategoryModel.java 566 2014-11-13 15:22:01Z sma $
 * %%
 * Copyright (C) 2013 - 2014 Fraunhofer FOKUS / CC ÖFIT
 * %%
 * Copyright (c) 2,013, Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1) Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 
 * 2) Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 
 * 3) All advertising materials mentioning features or use of this software must 
 *    display the following acknowledgement: 
 *    This product includes software developed by Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT.
 * 
 * 4) Neither the name of the organization nor the names of its contributors may 
 *    be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL 
 * Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Category service. Represents a row in the &quot;mvp_Category&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.movepla.model.impl.CategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.movepla.model.impl.CategoryImpl}.
 * </p>
 *
 * @author jpa
 * @see Category
 * @see de.fraunhofer.fokus.movepla.model.impl.CategoryImpl
 * @see de.fraunhofer.fokus.movepla.model.impl.CategoryModelImpl
 * @generated
 */
public interface CategoryModel extends BaseModel<Category> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a category model instance should use the {@link Category} interface instead.
     */

    /**
     * Returns the primary key of this category.
     *
     * @return the primary key of this category
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this category.
     *
     * @param primaryKey the primary key of this category
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the category ID of this category.
     *
     * @return the category ID of this category
     */
    public long getCategoryId();

    /**
     * Sets the category ID of this category.
     *
     * @param categoryId the category ID of this category
     */
    public void setCategoryId(long categoryId);

    /**
     * Returns the company ID of this category.
     *
     * @return the company ID of this category
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this category.
     *
     * @param companyId the company ID of this category
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this category.
     *
     * @return the user ID of this category
     */
    public long getUserId();

    /**
     * Sets the user ID of this category.
     *
     * @param userId the user ID of this category
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this category.
     *
     * @return the user uuid of this category
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this category.
     *
     * @param userUuid the user uuid of this category
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this category.
     *
     * @return the create date of this category
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this category.
     *
     * @param createDate the create date of this category
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this category.
     *
     * @return the modified date of this category
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this category.
     *
     * @param modifiedDate the modified date of this category
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the category name of this category.
     *
     * @return the category name of this category
     */
    @AutoEscape
    public String getCategoryName();

    /**
     * Sets the category name of this category.
     *
     * @param categoryName the category name of this category
     */
    public void setCategoryName(String categoryName);

    /**
     * Returns the parent category of this category.
     *
     * @return the parent category of this category
     */
    public long getParentCategory();

    /**
     * Sets the parent category of this category.
     *
     * @param parentCategory the parent category of this category
     */
    public void setParentCategory(long parentCategory);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Category category);

    public int hashCode();

    public CacheModel<Category> toCacheModel();

    public Category toEscapedModel();

    public String toString();

    public String toXmlString();
}
