package de.fraunhofer.fokus.movepla.model;

/*
 * #%L
 * govapps_data
 * $Id: RelatedApplicationsModel.java 566 2014-11-13 15:22:01Z sma $
 * %%
 * Copyright (C) 2013 - 2014 Fraunhofer FOKUS / CC ÖFIT
 * %%
 * Copyright (c) 2,013, Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1) Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 
 * 2) Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 
 * 3) All advertising materials mentioning features or use of this software must 
 *    display the following acknowledgement: 
 *    This product includes software developed by Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT.
 * 
 * 4) Neither the name of the organization nor the names of its contributors may 
 *    be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL 
 * Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RelatedApplications service. Represents a row in the &quot;mvp_RelatedApplications&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.movepla.model.impl.RelatedApplicationsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.movepla.model.impl.RelatedApplicationsImpl}.
 * </p>
 *
 * @author jpa
 * @see RelatedApplications
 * @see de.fraunhofer.fokus.movepla.model.impl.RelatedApplicationsImpl
 * @see de.fraunhofer.fokus.movepla.model.impl.RelatedApplicationsModelImpl
 * @generated
 */
public interface RelatedApplicationsModel extends BaseModel<RelatedApplications> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a related applications model instance should use the {@link RelatedApplications} interface instead.
     */

    /**
     * Returns the primary key of this related applications.
     *
     * @return the primary key of this related applications
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this related applications.
     *
     * @param primaryKey the primary key of this related applications
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the related applications i d of this related applications.
     *
     * @return the related applications i d of this related applications
     */
    public long getRelatedApplicationsID();

    /**
     * Sets the related applications i d of this related applications.
     *
     * @param RelatedApplicationsID the related applications i d of this related applications
     */
    public void setRelatedApplicationsID(long RelatedApplicationsID);

    /**
     * Returns the company ID of this related applications.
     *
     * @return the company ID of this related applications
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this related applications.
     *
     * @param companyId the company ID of this related applications
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this related applications.
     *
     * @return the user ID of this related applications
     */
    public long getUserId();

    /**
     * Sets the user ID of this related applications.
     *
     * @param userId the user ID of this related applications
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this related applications.
     *
     * @return the user uuid of this related applications
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this related applications.
     *
     * @param userUuid the user uuid of this related applications
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this related applications.
     *
     * @return the create date of this related applications
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this related applications.
     *
     * @param createDate the create date of this related applications
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this related applications.
     *
     * @return the modified date of this related applications
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this related applications.
     *
     * @param modifiedDate the modified date of this related applications
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the application ID of this related applications.
     *
     * @return the application ID of this related applications
     */
    public long getApplicationId();

    /**
     * Sets the application ID of this related applications.
     *
     * @param applicationId the application ID of this related applications
     */
    public void setApplicationId(long applicationId);

    /**
     * Returns the application id2 of this related applications.
     *
     * @return the application id2 of this related applications
     */
    public long getApplicationId2();

    /**
     * Sets the application id2 of this related applications.
     *
     * @param applicationId2 the application id2 of this related applications
     */
    public void setApplicationId2(long applicationId2);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(RelatedApplications relatedApplications);

    public int hashCode();

    public CacheModel<RelatedApplications> toCacheModel();

    public RelatedApplications toEscapedModel();

    public String toString();

    public String toXmlString();
}
