package com.govapps.persistence.model;

/*
 * #%L
 * govapps_concern
 * $Id: ConcernModel.java 566 2014-11-13 15:22:01Z sma $
 * %%
 * Copyright (C) 2013 - 2014 Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT
 * %%
 * Copyright (c) 2,013, Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1) Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 
 * 2) Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 
 * 3) All advertising materials mentioning features or use of this software must 
 *    display the following acknowledgement: 
 *    This product includes software developed by Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT.
 * 
 * 4) Neither the name of the organization nor the names of its contributors may 
 *    be used to endorse or promote products derived from this software without 
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL 
 * Fraunhofer FOKUS, Kompetenzzentrum Oeffentliche IT 
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Concern service. Represents a row in the &quot;CONC_Concern&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.govapps.persistence.model.impl.ConcernModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.govapps.persistence.model.impl.ConcernImpl}.
 * </p>
 *
 * @author ekl
 * @see Concern
 * @see com.govapps.persistence.model.impl.ConcernImpl
 * @see com.govapps.persistence.model.impl.ConcernModelImpl
 * @generated
 */
public interface ConcernModel extends BaseModel<Concern> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a concern model instance should use the {@link Concern} interface instead.
     */

    /**
     * Returns the primary key of this concern.
     *
     * @return the primary key of this concern
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this concern.
     *
     * @param primaryKey the primary key of this concern
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this concern.
     *
     * @return the ID of this concern
     */
    public long getId();

    /**
     * Sets the ID of this concern.
     *
     * @param id the ID of this concern
     */
    public void setId(long id);

    /**
     * Returns the company ID of this concern.
     *
     * @return the company ID of this concern
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this concern.
     *
     * @param companyId the company ID of this concern
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this concern.
     *
     * @return the group ID of this concern
     */
    public long getGroupId();

    /**
     * Sets the group ID of this concern.
     *
     * @param groupId the group ID of this concern
     */
    public void setGroupId(long groupId);

    /**
     * Returns the name of this concern.
     *
     * @return the name of this concern
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this concern.
     *
     * @param name the name of this concern
     */
    public void setName(String name);

    /**
     * Returns the email of this concern.
     *
     * @return the email of this concern
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this concern.
     *
     * @param email the email of this concern
     */
    public void setEmail(String email);

    /**
     * Returns the description of this concern.
     *
     * @return the description of this concern
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this concern.
     *
     * @param description the description of this concern
     */
    public void setDescription(String description);

    /**
     * Returns the platforms of this concern.
     *
     * @return the platforms of this concern
     */
    @AutoEscape
    public String getPlatforms();

    /**
     * Sets the platforms of this concern.
     *
     * @param platforms the platforms of this concern
     */
    public void setPlatforms(String platforms);

    /**
     * Returns the concern of this concern.
     *
     * @return the concern of this concern
     */
    public long getConcern();

    /**
     * Sets the concern of this concern.
     *
     * @param concern the concern of this concern
     */
    public void setConcern(long concern);

    /**
     * Returns the region of this concern.
     *
     * @return the region of this concern
     */
    @AutoEscape
    public String getRegion();

    /**
     * Sets the region of this concern.
     *
     * @param region the region of this concern
     */
    public void setRegion(String region);

    /**
     * Returns the category of this concern.
     *
     * @return the category of this concern
     */
    @AutoEscape
    public String getCategory();

    /**
     * Sets the category of this concern.
     *
     * @param category the category of this concern
     */
    public void setCategory(String category);

    /**
     * Returns the create date of this concern.
     *
     * @return the create date of this concern
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this concern.
     *
     * @param createDate the create date of this concern
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the supports of this concern.
     *
     * @return the supports of this concern
     */
    public long getSupports();

    /**
     * Sets the supports of this concern.
     *
     * @param supports the supports of this concern
     */
    public void setSupports(long supports);

    /**
     * Returns the state of this concern.
     *
     * @return the state of this concern
     */
    public int getState();

    /**
     * Sets the state of this concern.
     *
     * @param state the state of this concern
     */
    public void setState(int state);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Concern concern);

    public int hashCode();

    public CacheModel<Concern> toCacheModel();

    public Concern toEscapedModel();

    public String toString();

    public String toXmlString();
}
